/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.owns=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.FORCE_POLYFILL_PROMISE=!1;$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};$jscomp.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";$jscomp.polyfill=function(a,b,c,d){b&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(a,b,c,d):$jscomp.polyfillUnisolated(a,b,c,d))};
$jscomp.polyfillUnisolated=function(a,b){var c=$jscomp.global;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))return;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})};
$jscomp.polyfillIsolated=function(a,b,c){var d=a.split(".");a=1===d.length;var e=d[0];e=!a&&e in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var f=0;f<d.length-1;f++){var g=d[f];if(!(g in e))return;e=e[g]}d=d[d.length-1];c=$jscomp.IS_SYMBOL_NATIVE&&"es6"===c?e[d]:null;b=b(c);null!=b&&(a?$jscomp.defineProperty($jscomp.polyfills,d,{configurable:!0,writable:!0,value:b}):b!==c&&($jscomp.propertyToPolyfillSymbol[d]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(d):$jscomp.POLYFILL_PREFIX+d,
d=$jscomp.propertyToPolyfillSymbol[d],$jscomp.defineProperty(e,d,{configurable:!0,writable:!0,value:b})))};$jscomp.polyfill("Object.entries",function(a){return a?a:a=function(b){var c=[],d;for(d in b)$jscomp.owns(b,d)&&c.push([d,b[d]]);return c}},"es8","es3");
$jscomp.polyfill("Array.prototype.includes",function(a){return a?a:a=function(b,c){var d=this;d instanceof String&&(d=String(d));var e=d.length;c=c||0;for(0>c&&(c=Math.max(c+e,0));c<e;c++){var f=d[c];if(f===b||Object.is(f,b))return!0}return!1}},"es7","es3");$jscomp.polyfill("Object.values",function(a){return a?a:a=function(b){var c=[],d;for(d in b)$jscomp.owns(b,d)&&c.push(b[d]);return c}},"es8","es3");var goog=goog||{};goog.global=this||self;
goog.exportPath_=function(a,b,c,d){a=a.split(".");d=d||goog.global;a[0]in d||"undefined"==typeof d.execScript||d.execScript("var "+a[0]);for(var e;a.length&&(e=a.shift());)if(a.length||void 0===b)d=d[e]&&d[e]!==Object.prototype[e]?d[e]:d[e]={};else if(!c&&goog.isObject(b)&&goog.isObject(d[e]))for(var f in b)b.hasOwnProperty(f)&&(d[e][f]=b[f]);else d[e]=b};goog.define=function(a,b){return a=b};goog.FEATURESET_YEAR=2012;goog.DEBUG=!0;goog.LOCALE="en";goog.TRUSTED_SITE=!0;
goog.DISALLOW_TEST_ONLY_CODE=!goog.DEBUG;goog.ENABLE_CHROME_APP_SAFE_SCRIPT_LOADING=!1;goog.provide=function(a){if(goog.isInModuleLoader_())throw Error("goog.provide cannot be used within a module.");goog.constructNamespace_(a)};goog.constructNamespace_=function(a,b,c){goog.exportPath_(a,b,c)};goog.getScriptNonce=function(a){if(a&&a!=goog.global)return goog.getScriptNonce_(a.document);null===goog.cspNonce_&&(goog.cspNonce_=goog.getScriptNonce_(goog.global.document));return goog.cspNonce_};
goog.NONCE_PATTERN_=/^[\w+/_-]+[=]{0,2}$/;goog.cspNonce_=null;goog.getScriptNonce_=function(a){return(a=a.querySelector&&a.querySelector("script[nonce]"))&&(a=a.nonce||a.getAttribute("nonce"))&&goog.NONCE_PATTERN_.test(a)?a:""};goog.VALID_MODULE_RE_=/^[a-zA-Z_$][a-zA-Z0-9._$]*$/;
goog.module=function(a){if("string"!==typeof a||!a||-1==a.search(goog.VALID_MODULE_RE_))throw Error("Invalid module identifier");if(!goog.isInGoogModuleLoader_())throw Error("Module "+a+" has been loaded incorrectly. Note, modules cannot be loaded as normal scripts. They require some kind of pre-processing step. You're likely trying to load a module via a script tag or as a part of a concatenated bundle without rewriting the module. For more info see: https://github.com/google/closure-library/wiki/goog.module:-an-ES6-module-like-alternative-to-goog.provide.");if(goog.moduleLoaderState_.moduleName)throw Error("goog.module may only be called once per module.");
goog.moduleLoaderState_.moduleName=a};goog.module.get=function(){return null};goog.module.getInternal_=function(){return null};goog.ModuleType={ES6:"es6",GOOG:"goog"};goog.moduleLoaderState_=null;goog.isInModuleLoader_=function(){return goog.isInGoogModuleLoader_()||goog.isInEs6ModuleLoader_()};goog.isInGoogModuleLoader_=function(){return!!goog.moduleLoaderState_&&goog.moduleLoaderState_.type==goog.ModuleType.GOOG};
goog.isInEs6ModuleLoader_=function(){var a=!!goog.moduleLoaderState_&&goog.moduleLoaderState_.type==goog.ModuleType.ES6;return a?!0:(a=goog.global.$jscomp)?"function"!=typeof a.getCurrentModulePath?!1:!!a.getCurrentModulePath():!1};goog.module.declareLegacyNamespace=function(){goog.moduleLoaderState_.declareLegacyNamespace=!0};
goog.declareModuleId=function(a){if(goog.moduleLoaderState_)goog.moduleLoaderState_.moduleName=a;else{var b=goog.global.$jscomp;if(!b||"function"!=typeof b.getCurrentModulePath)throw Error('Module with namespace "'+a+'" has been loaded incorrectly.');b=b.require(b.getCurrentModulePath());goog.loadedModules_[a]={exports:b,type:goog.ModuleType.ES6,moduleId:a}}};
goog.setTestOnly=function(a){if(goog.DISALLOW_TEST_ONLY_CODE)throw a=a||"",Error("Importing test-only code into non-debug environment"+(a?": "+a:"."));};goog.forwardDeclare=function(){};goog.getObjectByName=function(a,b){a=a.split(".");b=b||goog.global;for(var c=0;c<a.length;c++)if(b=b[a[c]],null==b)return null;return b};goog.addDependency=function(){};goog.useStrictRequires=!1;goog.ENABLE_DEBUG_LOADER=!0;goog.logToConsole_=function(a){goog.global.console&&goog.global.console.error(a)};
goog.require=function(){};goog.requireType=function(){return{}};goog.basePath="";goog.nullFunction=function(){};goog.abstractMethod=function(){throw Error("unimplemented abstract method");};goog.addSingletonGetter=function(a){a.instance_=void 0;a.getInstance=function(){if(a.instance_)return a.instance_;goog.DEBUG&&(goog.instantiatedSingletons_[goog.instantiatedSingletons_.length]=a);return a.instance_=new a}};goog.instantiatedSingletons_=[];goog.LOAD_MODULE_USING_EVAL=!0;
goog.SEAL_MODULE_EXPORTS=goog.DEBUG;goog.loadedModules_={};goog.DEPENDENCIES_ENABLED=!1;goog.TRANSPILE="detect";goog.ASSUME_ES_MODULES_TRANSPILED=!1;goog.TRANSPILE_TO_LANGUAGE="";goog.TRANSPILER="transpile.js";goog.hasBadLetScoping=null;
goog.loadModule=function(a){var b=goog.moduleLoaderState_;try{goog.moduleLoaderState_={moduleName:"",declareLegacyNamespace:!1,type:goog.ModuleType.GOOG};var c={},d=c;if("function"===typeof a)d=a.call(void 0,d);else if("string"===typeof a)d=goog.loadModuleFromSource_.call(void 0,d,a);else throw Error("Invalid module definition");var e=goog.moduleLoaderState_.moduleName;if("string"===typeof e&&e){goog.moduleLoaderState_.declareLegacyNamespace?(a=c!==d,goog.constructNamespace_(e,d,a)):goog.SEAL_MODULE_EXPORTS&&
Object.seal&&"object"==typeof d&&null!=d&&Object.seal(d);var f={exports:d,type:goog.ModuleType.GOOG,moduleId:goog.moduleLoaderState_.moduleName};goog.loadedModules_[e]=f}else throw Error('Invalid module name "'+e+'"');}finally{goog.moduleLoaderState_=b}};goog.loadModuleFromSource_=function(a,b){eval(goog.CLOSURE_EVAL_PREFILTER_.createScript(b));return a};
goog.normalizePath_=function(a){a=a.split("/");for(var b=0;b<a.length;)"."==a[b]?a.splice(b,1):b&&".."==a[b]&&a[b-1]&&".."!=a[b-1]?a.splice(--b,2):b++;return a.join("/")};goog.loadFileSync_=function(a){if(goog.global.CLOSURE_LOAD_FILE_SYNC)return goog.global.CLOSURE_LOAD_FILE_SYNC(a);try{var b=new goog.global.XMLHttpRequest;b.open("get",a,!1);b.send();return 0==b.status||200==b.status?b.responseText:null}catch(c){return null}};
goog.transpile_=function(a,b,c){var d=goog.global.$jscomp;d||(goog.global.$jscomp=d={});var e=d.transpile;if(!e){var f=goog.basePath+goog.TRANSPILER,g=goog.loadFileSync_(f);if(g){(function(){(0,eval)(g+"\n//# sourceURL="+f)}).call(goog.global);if(goog.global.$gwtExport&&goog.global.$gwtExport.$jscomp&&!goog.global.$gwtExport.$jscomp.transpile)throw Error('The transpiler did not properly export the "transpile" method. $gwtExport: '+JSON.stringify(goog.global.$gwtExport));goog.global.$jscomp.transpile=
goog.global.$gwtExport.$jscomp.transpile;d=goog.global.$jscomp;e=d.transpile}}if(!e){var h=" requires transpilation but no transpiler was found.";h+=' Please add "//javascript/closure:transpiler" as a data dependency to ensure it is included.';e=d.transpile=function(k,l){goog.logToConsole_(l+h);return k}}return e(a,b,c)};goog.typeOf=function(a){var b=typeof a;return"object"!=b?b:a?Array.isArray(a)?"array":b:"null"};
goog.isArrayLike=function(a){var b=goog.typeOf(a);return"array"==b||"object"==b&&"number"==typeof a.length};goog.isDateLike=function(a){return goog.isObject(a)&&"function"==typeof a.getFullYear};goog.isObject=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b};goog.getUid=function(a){return Object.prototype.hasOwnProperty.call(a,goog.UID_PROPERTY_)&&a[goog.UID_PROPERTY_]||(a[goog.UID_PROPERTY_]=++goog.uidCounter_)};goog.hasUid=function(a){return!!a[goog.UID_PROPERTY_]};
goog.removeUid=function(a){null!==a&&"removeAttribute"in a&&a.removeAttribute(goog.UID_PROPERTY_);try{delete a[goog.UID_PROPERTY_]}catch(b){}};goog.UID_PROPERTY_="closure_uid_"+(1E9*Math.random()>>>0);goog.uidCounter_=0;goog.cloneObject=function(a){var b=goog.typeOf(a);if("object"==b||"array"==b){if("function"===typeof a.clone)return a.clone();b="array"==b?[]:{};for(var c in a)b[c]=goog.cloneObject(a[c]);return b}return a};goog.bindNative_=function(a,b,c){return a.call.apply(a.bind,arguments)};
goog.bindJs_=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var e=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(e,d);return a.apply(b,e)}}return function(){return a.apply(b,arguments)}};goog.bind=function(a,b,c){goog.bind=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?goog.bindNative_:goog.bindJs_;return goog.bind.apply(null,arguments)};
goog.partial=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var d=c.slice();d.push.apply(d,arguments);return a.apply(this,d)}};goog.mixin=function(a,b){for(var c in b)a[c]=b[c]};goog.now=function(){return Date.now()};goog.globalEval=function(a){(0,eval)(a)};
goog.getCssName=function(a,b){if("."==String(a).charAt(0))throw Error('className passed in goog.getCssName must not start with ".". You passed: '+a);var c=function(e){return goog.cssNameMapping_[e]||e},d=function(e){e=e.split("-");for(var f=[],g=0;g<e.length;g++)f.push(c(e[g]));return f.join("-")};d=goog.cssNameMapping_?"BY_WHOLE"==goog.cssNameMappingStyle_?c:d:function(e){return e};a=b?a+"-"+d(b):d(a);return goog.global.CLOSURE_CSS_NAME_MAP_FN?goog.global.CLOSURE_CSS_NAME_MAP_FN(a):a};
goog.setCssNameMapping=function(a,b){goog.cssNameMapping_=a;goog.cssNameMappingStyle_=b};goog.getMsg=function(a,b,c){c&&c.html&&(a=a.replace(/</g,"&lt;"));c&&c.unescapeHtmlEntities&&(a=a.replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/&apos;/g,"'").replace(/&quot;/g,'"').replace(/&amp;/g,"&"));b&&(a=a.replace(/\{\$([^}]+)}/g,function(d,e){return null!=b&&e in b?b[e]:d}));return a};goog.getMsgWithFallback=function(a){return a};goog.exportSymbol=function(a,b,c){goog.exportPath_(a,b,!0,c)};
goog.exportProperty=function(a,b,c){a[b]=c};goog.inherits=function(a,b){function c(){}c.prototype=b.prototype;a.superClass_=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.base=function(d,e,f){for(var g=Array(arguments.length-2),h=2;h<arguments.length;h++)g[h-2]=arguments[h];return b.prototype[e].apply(d,g)}};goog.scope=function(a){if(goog.isInModuleLoader_())throw Error("goog.scope is not supported within a module.");a.call(goog.global)};
goog.defineClass=function(a,b){var c=b.constructor,d=b.statics;c&&c!=Object.prototype.constructor||(c=function(){throw Error("cannot instantiate an interface (no constructor defined).");});c=goog.defineClass.createSealingConstructor_(c,a);a&&goog.inherits(c,a);delete b.constructor;delete b.statics;goog.defineClass.applyProperties_(c.prototype,b);null!=d&&(d instanceof Function?d(c):goog.defineClass.applyProperties_(c,d));return c};goog.defineClass.SEAL_CLASS_INSTANCES=goog.DEBUG;
goog.defineClass.createSealingConstructor_=function(a){if(!goog.defineClass.SEAL_CLASS_INSTANCES)return a;var b=function(){var c=a.apply(this,arguments)||this;c[goog.UID_PROPERTY_]=c[goog.UID_PROPERTY_];return c};return b};goog.defineClass.OBJECT_PROTOTYPE_FIELDS_="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");
goog.defineClass.applyProperties_=function(a,b){for(var c in b)Object.prototype.hasOwnProperty.call(b,c)&&(a[c]=b[c]);for(var d=0;d<goog.defineClass.OBJECT_PROTOTYPE_FIELDS_.length;d++)c=goog.defineClass.OBJECT_PROTOTYPE_FIELDS_[d],Object.prototype.hasOwnProperty.call(b,c)&&(a[c]=b[c])};goog.TRUSTED_TYPES_POLICY_NAME="goog";goog.identity_=function(a){return a};
goog.createTrustedTypesPolicy=function(a){var b=null,c=goog.global.trustedTypes;if(!c||!c.createPolicy)return b;try{b=c.createPolicy(a,{createHTML:goog.identity_,createScript:goog.identity_,createScriptURL:goog.identity_})}catch(d){goog.logToConsole_(d.message)}return b};/*

 Copyright 2016 Google Inc. All rights reserved.
 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.

 @author lwe@google.com (Lukas Weichselbaum)
*/
var module$exports$google3$javascript$security$csp$csp_evaluator$finding={Finding:class{constructor(a,b,c,d,e){this.type=a;this.description=b;this.severity=c;this.value=e}},Severity:{HIGH:10,SYNTAX:20,MEDIUM:30,HIGH_MAYBE:40,STRICT_CSP:45,MEDIUM_MAYBE:50,INFO:60,NONE:100}};module$exports$google3$javascript$security$csp$csp_evaluator$finding.Severity[module$exports$google3$javascript$security$csp$csp_evaluator$finding.Severity.HIGH]="HIGH";
module$exports$google3$javascript$security$csp$csp_evaluator$finding.Severity[module$exports$google3$javascript$security$csp$csp_evaluator$finding.Severity.SYNTAX]="SYNTAX";module$exports$google3$javascript$security$csp$csp_evaluator$finding.Severity[module$exports$google3$javascript$security$csp$csp_evaluator$finding.Severity.MEDIUM]="MEDIUM";
module$exports$google3$javascript$security$csp$csp_evaluator$finding.Severity[module$exports$google3$javascript$security$csp$csp_evaluator$finding.Severity.HIGH_MAYBE]="HIGH_MAYBE";module$exports$google3$javascript$security$csp$csp_evaluator$finding.Severity[module$exports$google3$javascript$security$csp$csp_evaluator$finding.Severity.STRICT_CSP]="STRICT_CSP";
module$exports$google3$javascript$security$csp$csp_evaluator$finding.Severity[module$exports$google3$javascript$security$csp$csp_evaluator$finding.Severity.MEDIUM_MAYBE]="MEDIUM_MAYBE";module$exports$google3$javascript$security$csp$csp_evaluator$finding.Severity[module$exports$google3$javascript$security$csp$csp_evaluator$finding.Severity.INFO]="INFO";
module$exports$google3$javascript$security$csp$csp_evaluator$finding.Severity[module$exports$google3$javascript$security$csp$csp_evaluator$finding.Severity.NONE]="NONE";
module$exports$google3$javascript$security$csp$csp_evaluator$finding.Type={MISSING_SEMICOLON:100,UNKNOWN_DIRECTIVE:101,INVALID_KEYWORD:102,MISSING_DIRECTIVES:300,SCRIPT_UNSAFE_INLINE:301,SCRIPT_UNSAFE_EVAL:302,PLAIN_URL_SCHEMES:303,PLAIN_WILDCARD:304,SCRIPT_WHITELIST_BYPASS:305,OBJECT_WHITELIST_BYPASS:306,NONCE_LENGTH:307,IP_SOURCE:308,DEPRECATED_DIRECTIVE:309,SRC_HTTP:310,STRICT_DYNAMIC:400,STRICT_DYNAMIC_NOT_STANDALONE:401,NONCE_HASH:402,UNSAFE_INLINE_FALLBACK:403,WHITELIST_FALLBACK:404,IGNORED:405,
REQUIRE_TRUSTED_TYPES_FOR_SCRIPTS:500};module$exports$google3$javascript$security$csp$csp_evaluator$finding.Type[module$exports$google3$javascript$security$csp$csp_evaluator$finding.Type.MISSING_SEMICOLON]="MISSING_SEMICOLON";module$exports$google3$javascript$security$csp$csp_evaluator$finding.Type[module$exports$google3$javascript$security$csp$csp_evaluator$finding.Type.UNKNOWN_DIRECTIVE]="UNKNOWN_DIRECTIVE";
module$exports$google3$javascript$security$csp$csp_evaluator$finding.Type[module$exports$google3$javascript$security$csp$csp_evaluator$finding.Type.INVALID_KEYWORD]="INVALID_KEYWORD";module$exports$google3$javascript$security$csp$csp_evaluator$finding.Type[module$exports$google3$javascript$security$csp$csp_evaluator$finding.Type.MISSING_DIRECTIVES]="MISSING_DIRECTIVES";
module$exports$google3$javascript$security$csp$csp_evaluator$finding.Type[module$exports$google3$javascript$security$csp$csp_evaluator$finding.Type.SCRIPT_UNSAFE_INLINE]="SCRIPT_UNSAFE_INLINE";module$exports$google3$javascript$security$csp$csp_evaluator$finding.Type[module$exports$google3$javascript$security$csp$csp_evaluator$finding.Type.SCRIPT_UNSAFE_EVAL]="SCRIPT_UNSAFE_EVAL";
module$exports$google3$javascript$security$csp$csp_evaluator$finding.Type[module$exports$google3$javascript$security$csp$csp_evaluator$finding.Type.PLAIN_URL_SCHEMES]="PLAIN_URL_SCHEMES";module$exports$google3$javascript$security$csp$csp_evaluator$finding.Type[module$exports$google3$javascript$security$csp$csp_evaluator$finding.Type.PLAIN_WILDCARD]="PLAIN_WILDCARD";
module$exports$google3$javascript$security$csp$csp_evaluator$finding.Type[module$exports$google3$javascript$security$csp$csp_evaluator$finding.Type.SCRIPT_WHITELIST_BYPASS]="SCRIPT_WHITELIST_BYPASS";module$exports$google3$javascript$security$csp$csp_evaluator$finding.Type[module$exports$google3$javascript$security$csp$csp_evaluator$finding.Type.OBJECT_WHITELIST_BYPASS]="OBJECT_WHITELIST_BYPASS";
module$exports$google3$javascript$security$csp$csp_evaluator$finding.Type[module$exports$google3$javascript$security$csp$csp_evaluator$finding.Type.NONCE_LENGTH]="NONCE_LENGTH";module$exports$google3$javascript$security$csp$csp_evaluator$finding.Type[module$exports$google3$javascript$security$csp$csp_evaluator$finding.Type.IP_SOURCE]="IP_SOURCE";
module$exports$google3$javascript$security$csp$csp_evaluator$finding.Type[module$exports$google3$javascript$security$csp$csp_evaluator$finding.Type.DEPRECATED_DIRECTIVE]="DEPRECATED_DIRECTIVE";module$exports$google3$javascript$security$csp$csp_evaluator$finding.Type[module$exports$google3$javascript$security$csp$csp_evaluator$finding.Type.SRC_HTTP]="SRC_HTTP";
module$exports$google3$javascript$security$csp$csp_evaluator$finding.Type[module$exports$google3$javascript$security$csp$csp_evaluator$finding.Type.STRICT_DYNAMIC]="STRICT_DYNAMIC";module$exports$google3$javascript$security$csp$csp_evaluator$finding.Type[module$exports$google3$javascript$security$csp$csp_evaluator$finding.Type.STRICT_DYNAMIC_NOT_STANDALONE]="STRICT_DYNAMIC_NOT_STANDALONE";
module$exports$google3$javascript$security$csp$csp_evaluator$finding.Type[module$exports$google3$javascript$security$csp$csp_evaluator$finding.Type.NONCE_HASH]="NONCE_HASH";module$exports$google3$javascript$security$csp$csp_evaluator$finding.Type[module$exports$google3$javascript$security$csp$csp_evaluator$finding.Type.UNSAFE_INLINE_FALLBACK]="UNSAFE_INLINE_FALLBACK";
module$exports$google3$javascript$security$csp$csp_evaluator$finding.Type[module$exports$google3$javascript$security$csp$csp_evaluator$finding.Type.WHITELIST_FALLBACK]="WHITELIST_FALLBACK";module$exports$google3$javascript$security$csp$csp_evaluator$finding.Type[module$exports$google3$javascript$security$csp$csp_evaluator$finding.Type.IGNORED]="IGNORED";
module$exports$google3$javascript$security$csp$csp_evaluator$finding.Type[module$exports$google3$javascript$security$csp$csp_evaluator$finding.Type.REQUIRE_TRUSTED_TYPES_FOR_SCRIPTS]="REQUIRE_TRUSTED_TYPES_FOR_SCRIPTS";/*

 Copyright 2016 Google Inc. All rights reserved.
 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.

*/
var module$exports$google3$javascript$security$csp$csp_evaluator$csp={Csp:class{static clone(a){const b=new module$exports$google3$javascript$security$csp$csp_evaluator$csp.Csp;for(const [c,d]of Object.entries(a))d&&(b[c]=[...d]);return b}},Keyword:{SELF:"'self'",NONE:"'none'",UNSAFE_INLINE:"'unsafe-inline'",UNSAFE_EVAL:"'unsafe-eval'",WASM_EVAL:"'wasm-eval'",WASM_UNSAFE_EVAL:"'wasm-unsafe-eval'",STRICT_DYNAMIC:"'strict-dynamic'",UNSAFE_HASHED_ATTRIBUTES:"'unsafe-hashed-attributes'",UNSAFE_HASHES:"'unsafe-hashes'",
REPORT_SAMPLE:"'report-sample'"},TrustedTypesSink:{SCRIPT:"'script'"},Directive:{CHILD_SRC:"child-src",CONNECT_SRC:"connect-src",DEFAULT_SRC:"default-src",FONT_SRC:"font-src",FRAME_SRC:"frame-src",IMG_SRC:"img-src",MEDIA_SRC:"media-src",OBJECT_SRC:"object-src",SCRIPT_SRC:"script-src",SCRIPT_SRC_ATTR:"script-src-attr",SCRIPT_SRC_ELEM:"script-src-elem",STYLE_SRC:"style-src",STYLE_SRC_ATTR:"style-src-attr",STYLE_SRC_ELEM:"style-src-elem",PREFETCH_SRC:"prefetch-src",MANIFEST_SRC:"manifest-src",WORKER_SRC:"worker-src",
BASE_URI:"base-uri",PLUGIN_TYPES:"plugin-types",SANDBOX:"sandbox",DISOWN_OPENER:"disown-opener",FORM_ACTION:"form-action",FRAME_ANCESTORS:"frame-ancestors",REPORT_TO:"report-to",REPORT_URI:"report-uri",BLOCK_ALL_MIXED_CONTENT:"block-all-mixed-content",UPGRADE_INSECURE_REQUESTS:"upgrade-insecure-requests",REFLECTED_XSS:"reflected-xss",REFERRER:"referrer",REQUIRE_SRI_FOR:"require-sri-for",TRUSTED_TYPES:"trusted-types",REQUIRE_TRUSTED_TYPES_FOR:"require-trusted-types-for"}};
module$exports$google3$javascript$security$csp$csp_evaluator$csp.FETCH_DIRECTIVES=[module$exports$google3$javascript$security$csp$csp_evaluator$csp.Directive.CHILD_SRC,module$exports$google3$javascript$security$csp$csp_evaluator$csp.Directive.CONNECT_SRC,module$exports$google3$javascript$security$csp$csp_evaluator$csp.Directive.DEFAULT_SRC,module$exports$google3$javascript$security$csp$csp_evaluator$csp.Directive.FONT_SRC,module$exports$google3$javascript$security$csp$csp_evaluator$csp.Directive.FRAME_SRC,
module$exports$google3$javascript$security$csp$csp_evaluator$csp.Directive.IMG_SRC,module$exports$google3$javascript$security$csp$csp_evaluator$csp.Directive.MANIFEST_SRC,module$exports$google3$javascript$security$csp$csp_evaluator$csp.Directive.MEDIA_SRC,module$exports$google3$javascript$security$csp$csp_evaluator$csp.Directive.OBJECT_SRC,module$exports$google3$javascript$security$csp$csp_evaluator$csp.Directive.SCRIPT_SRC,module$exports$google3$javascript$security$csp$csp_evaluator$csp.Directive.SCRIPT_SRC_ATTR,
module$exports$google3$javascript$security$csp$csp_evaluator$csp.Directive.SCRIPT_SRC_ELEM,module$exports$google3$javascript$security$csp$csp_evaluator$csp.Directive.STYLE_SRC,module$exports$google3$javascript$security$csp$csp_evaluator$csp.Directive.STYLE_SRC_ATTR,module$exports$google3$javascript$security$csp$csp_evaluator$csp.Directive.STYLE_SRC_ELEM,module$exports$google3$javascript$security$csp$csp_evaluator$csp.Directive.WORKER_SRC];
module$exports$google3$javascript$security$csp$csp_evaluator$csp.Version={CSP1:1,CSP2:2,CSP3:3};module$exports$google3$javascript$security$csp$csp_evaluator$csp.Version[module$exports$google3$javascript$security$csp$csp_evaluator$csp.Version.CSP1]="CSP1";module$exports$google3$javascript$security$csp$csp_evaluator$csp.Version[module$exports$google3$javascript$security$csp$csp_evaluator$csp.Version.CSP2]="CSP2";
module$exports$google3$javascript$security$csp$csp_evaluator$csp.Version[module$exports$google3$javascript$security$csp$csp_evaluator$csp.Version.CSP3]="CSP3";function module$contents$google3$javascript$security$csp$csp_evaluator$csp_isDirective(a){return Object.values(module$exports$google3$javascript$security$csp$csp_evaluator$csp.Directive).includes(a)}module$exports$google3$javascript$security$csp$csp_evaluator$csp.isDirective=module$contents$google3$javascript$security$csp$csp_evaluator$csp_isDirective;
function module$contents$google3$javascript$security$csp$csp_evaluator$csp_isKeyword(a){return Object.values(module$exports$google3$javascript$security$csp$csp_evaluator$csp.Keyword).includes(a)}module$exports$google3$javascript$security$csp$csp_evaluator$csp.isKeyword=module$contents$google3$javascript$security$csp$csp_evaluator$csp_isKeyword;function module$contents$google3$javascript$security$csp$csp_evaluator$csp_isUrlScheme(a){const b=/^[a-zA-Z][+a-zA-Z0-9.-]*:$/;return b.test(a)}
module$exports$google3$javascript$security$csp$csp_evaluator$csp.isUrlScheme=module$contents$google3$javascript$security$csp$csp_evaluator$csp_isUrlScheme;module$exports$google3$javascript$security$csp$csp_evaluator$csp.STRICT_NONCE_PATTERN=/^'nonce-[a-zA-Z0-9+/_-]+[=]{0,2}'$/;module$exports$google3$javascript$security$csp$csp_evaluator$csp.NONCE_PATTERN=/^'nonce-(.+)'$/;
function module$contents$google3$javascript$security$csp$csp_evaluator$csp_isNonce(a,b){b=b?module$exports$google3$javascript$security$csp$csp_evaluator$csp.STRICT_NONCE_PATTERN:module$exports$google3$javascript$security$csp$csp_evaluator$csp.NONCE_PATTERN;return b.test(a)}module$exports$google3$javascript$security$csp$csp_evaluator$csp.isNonce=module$contents$google3$javascript$security$csp$csp_evaluator$csp_isNonce;
module$exports$google3$javascript$security$csp$csp_evaluator$csp.STRICT_HASH_PATTERN=/^'(sha256|sha384|sha512)-[a-zA-Z0-9+/]+[=]{0,2}'$/;module$exports$google3$javascript$security$csp$csp_evaluator$csp.HASH_PATTERN=/^'(sha256|sha384|sha512)-(.+)'$/;
function module$contents$google3$javascript$security$csp$csp_evaluator$csp_isHash(a,b){b=b?module$exports$google3$javascript$security$csp$csp_evaluator$csp.STRICT_HASH_PATTERN:module$exports$google3$javascript$security$csp$csp_evaluator$csp.HASH_PATTERN;return b.test(a)}module$exports$google3$javascript$security$csp$csp_evaluator$csp.isHash=module$contents$google3$javascript$security$csp$csp_evaluator$csp_isHash;module$exports$google3$javascript$security$csp$csp_evaluator$csp.CspError=class extends Error{constructor(a){super(a)}};/*

 Copyright 2016 Google Inc. All rights reserved.
 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/


module.exports = goog;