/**
 * @license Copyright 2018 Google Inc. All Rights Reserved.
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
 */

// Generated by `yarn update:crdp-typings`

declare global {
  module LH {
    export interface CrdpEvents {
      'Console.messageAdded': Crdp.Console.MessageAddedEvent;
      'Debugger.breakpointResolved': Crdp.Debugger.BreakpointResolvedEvent;
      'Debugger.paused': Crdp.Debugger.PausedEvent;
      'Debugger.resumed': void;
      'Debugger.scriptFailedToParse': Crdp.Debugger.ScriptFailedToParseEvent;
      'Debugger.scriptParsed': Crdp.Debugger.ScriptParsedEvent;
      'HeapProfiler.addHeapSnapshotChunk': Crdp.HeapProfiler.AddHeapSnapshotChunkEvent;
      'HeapProfiler.heapStatsUpdate': Crdp.HeapProfiler.HeapStatsUpdateEvent;
      'HeapProfiler.lastSeenObjectId': Crdp.HeapProfiler.LastSeenObjectIdEvent;
      'HeapProfiler.reportHeapSnapshotProgress': Crdp.HeapProfiler.ReportHeapSnapshotProgressEvent;
      'HeapProfiler.resetProfiles': void;
      'Profiler.consoleProfileFinished': Crdp.Profiler.ConsoleProfileFinishedEvent;
      'Profiler.consoleProfileStarted': Crdp.Profiler.ConsoleProfileStartedEvent;
      'Runtime.consoleAPICalled': Crdp.Runtime.ConsoleAPICalledEvent;
      'Runtime.exceptionRevoked': Crdp.Runtime.ExceptionRevokedEvent;
      'Runtime.exceptionThrown': Crdp.Runtime.ExceptionThrownEvent;
      'Runtime.executionContextCreated': Crdp.Runtime.ExecutionContextCreatedEvent;
      'Runtime.executionContextDestroyed': Crdp.Runtime.ExecutionContextDestroyedEvent;
      'Runtime.executionContextsCleared': void;
      'Runtime.inspectRequested': Crdp.Runtime.InspectRequestedEvent;
      'Animation.animationCanceled': Crdp.Animation.AnimationCanceledEvent;
      'Animation.animationCreated': Crdp.Animation.AnimationCreatedEvent;
      'Animation.animationStarted': Crdp.Animation.AnimationStartedEvent;
      'ApplicationCache.applicationCacheStatusUpdated': Crdp.ApplicationCache.ApplicationCacheStatusUpdatedEvent;
      'ApplicationCache.networkStateUpdated': Crdp.ApplicationCache.NetworkStateUpdatedEvent;
      'CSS.fontsUpdated': void;
      'CSS.mediaQueryResultChanged': void;
      'CSS.styleSheetAdded': Crdp.CSS.StyleSheetAddedEvent;
      'CSS.styleSheetChanged': Crdp.CSS.StyleSheetChangedEvent;
      'CSS.styleSheetRemoved': Crdp.CSS.StyleSheetRemovedEvent;
      'DOM.attributeModified': Crdp.DOM.AttributeModifiedEvent;
      'DOM.attributeRemoved': Crdp.DOM.AttributeRemovedEvent;
      'DOM.characterDataModified': Crdp.DOM.CharacterDataModifiedEvent;
      'DOM.childNodeCountUpdated': Crdp.DOM.ChildNodeCountUpdatedEvent;
      'DOM.childNodeInserted': Crdp.DOM.ChildNodeInsertedEvent;
      'DOM.childNodeRemoved': Crdp.DOM.ChildNodeRemovedEvent;
      'DOM.distributedNodesUpdated': Crdp.DOM.DistributedNodesUpdatedEvent;
      'DOM.documentUpdated': void;
      'DOM.inlineStyleInvalidated': Crdp.DOM.InlineStyleInvalidatedEvent;
      'DOM.pseudoElementAdded': Crdp.DOM.PseudoElementAddedEvent;
      'DOM.pseudoElementRemoved': Crdp.DOM.PseudoElementRemovedEvent;
      'DOM.setChildNodes': Crdp.DOM.SetChildNodesEvent;
      'DOM.shadowRootPopped': Crdp.DOM.ShadowRootPoppedEvent;
      'DOM.shadowRootPushed': Crdp.DOM.ShadowRootPushedEvent;
      'DOMStorage.domStorageItemAdded': Crdp.DOMStorage.DomStorageItemAddedEvent;
      'DOMStorage.domStorageItemRemoved': Crdp.DOMStorage.DomStorageItemRemovedEvent;
      'DOMStorage.domStorageItemUpdated': Crdp.DOMStorage.DomStorageItemUpdatedEvent;
      'DOMStorage.domStorageItemsCleared': Crdp.DOMStorage.DomStorageItemsClearedEvent;
      'Database.addDatabase': Crdp.Database.AddDatabaseEvent;
      'Emulation.virtualTimeAdvanced': Crdp.Emulation.VirtualTimeAdvancedEvent;
      'Emulation.virtualTimeBudgetExpired': void;
      'Emulation.virtualTimePaused': Crdp.Emulation.VirtualTimePausedEvent;
      'HeadlessExperimental.mainFrameReadyForScreenshots': void;
      'HeadlessExperimental.needsBeginFramesChanged': Crdp.HeadlessExperimental.NeedsBeginFramesChangedEvent;
      'Inspector.detached': Crdp.Inspector.DetachedEvent;
      'Inspector.targetCrashed': void;
      'LayerTree.layerPainted': Crdp.LayerTree.LayerPaintedEvent;
      'LayerTree.layerTreeDidChange': Crdp.LayerTree.LayerTreeDidChangeEvent;
      'Log.entryAdded': Crdp.Log.EntryAddedEvent;
      'Network.dataReceived': Crdp.Network.DataReceivedEvent;
      'Network.eventSourceMessageReceived': Crdp.Network.EventSourceMessageReceivedEvent;
      'Network.loadingFailed': Crdp.Network.LoadingFailedEvent;
      'Network.loadingFinished': Crdp.Network.LoadingFinishedEvent;
      'Network.requestIntercepted': Crdp.Network.RequestInterceptedEvent;
      'Network.requestServedFromCache': Crdp.Network.RequestServedFromCacheEvent;
      'Network.requestWillBeSent': Crdp.Network.RequestWillBeSentEvent;
      'Network.resourceChangedPriority': Crdp.Network.ResourceChangedPriorityEvent;
      'Network.responseReceived': Crdp.Network.ResponseReceivedEvent;
      'Network.webSocketClosed': Crdp.Network.WebSocketClosedEvent;
      'Network.webSocketCreated': Crdp.Network.WebSocketCreatedEvent;
      'Network.webSocketFrameError': Crdp.Network.WebSocketFrameErrorEvent;
      'Network.webSocketFrameReceived': Crdp.Network.WebSocketFrameReceivedEvent;
      'Network.webSocketFrameSent': Crdp.Network.WebSocketFrameSentEvent;
      'Network.webSocketHandshakeResponseReceived': Crdp.Network.WebSocketHandshakeResponseReceivedEvent;
      'Network.webSocketWillSendHandshakeRequest': Crdp.Network.WebSocketWillSendHandshakeRequestEvent;
      'Overlay.inspectNodeRequested': Crdp.Overlay.InspectNodeRequestedEvent;
      'Overlay.nodeHighlightRequested': Crdp.Overlay.NodeHighlightRequestedEvent;
      'Overlay.screenshotRequested': Crdp.Overlay.ScreenshotRequestedEvent;
      'Page.domContentEventFired': Crdp.Page.DomContentEventFiredEvent;
      'Page.frameAttached': Crdp.Page.FrameAttachedEvent;
      'Page.frameClearedScheduledNavigation': Crdp.Page.FrameClearedScheduledNavigationEvent;
      'Page.frameDetached': Crdp.Page.FrameDetachedEvent;
      'Page.frameNavigated': Crdp.Page.FrameNavigatedEvent;
      'Page.frameResized': void;
      'Page.frameScheduledNavigation': Crdp.Page.FrameScheduledNavigationEvent;
      'Page.frameStartedLoading': Crdp.Page.FrameStartedLoadingEvent;
      'Page.frameStoppedLoading': Crdp.Page.FrameStoppedLoadingEvent;
      'Page.interstitialHidden': void;
      'Page.interstitialShown': void;
      'Page.javascriptDialogClosed': Crdp.Page.JavascriptDialogClosedEvent;
      'Page.javascriptDialogOpening': Crdp.Page.JavascriptDialogOpeningEvent;
      'Page.lifecycleEvent': Crdp.Page.LifecycleEventEvent;
      'Page.loadEventFired': Crdp.Page.LoadEventFiredEvent;
      'Page.screencastFrame': Crdp.Page.ScreencastFrameEvent;
      'Page.screencastVisibilityChanged': Crdp.Page.ScreencastVisibilityChangedEvent;
      'Page.windowOpen': Crdp.Page.WindowOpenEvent;
      'Performance.metrics': Crdp.Performance.MetricsEvent;
      'Security.certificateError': Crdp.Security.CertificateErrorEvent;
      'Security.securityStateChanged': Crdp.Security.SecurityStateChangedEvent;
      'ServiceWorker.workerErrorReported': Crdp.ServiceWorker.WorkerErrorReportedEvent;
      'ServiceWorker.workerRegistrationUpdated': Crdp.ServiceWorker.WorkerRegistrationUpdatedEvent;
      'ServiceWorker.workerVersionUpdated': Crdp.ServiceWorker.WorkerVersionUpdatedEvent;
      'Storage.cacheStorageContentUpdated': Crdp.Storage.CacheStorageContentUpdatedEvent;
      'Storage.cacheStorageListUpdated': Crdp.Storage.CacheStorageListUpdatedEvent;
      'Storage.indexedDBContentUpdated': Crdp.Storage.IndexedDBContentUpdatedEvent;
      'Storage.indexedDBListUpdated': Crdp.Storage.IndexedDBListUpdatedEvent;
      'Target.attachedToTarget': Crdp.Target.AttachedToTargetEvent;
      'Target.detachedFromTarget': Crdp.Target.DetachedFromTargetEvent;
      'Target.receivedMessageFromTarget': Crdp.Target.ReceivedMessageFromTargetEvent;
      'Target.targetCreated': Crdp.Target.TargetCreatedEvent;
      'Target.targetDestroyed': Crdp.Target.TargetDestroyedEvent;
      'Target.targetInfoChanged': Crdp.Target.TargetInfoChangedEvent;
      'Tethering.accepted': Crdp.Tethering.AcceptedEvent;
      'Tracing.bufferUsage': Crdp.Tracing.BufferUsageEvent;
      'Tracing.dataCollected': Crdp.Tracing.DataCollectedEvent;
      'Tracing.tracingComplete': Crdp.Tracing.TracingCompleteEvent;
    }
  }
}

// empty export to keep file a module
export {}
