'use strict';

module.exports = {
  CSSUsage: 'navigation',
  JsUsage: 'navigation',
  ViewportDimensions: 'snapshot',
  RuntimeExceptions: 'timespan',
  ConsoleMessages: 'timespan',
  AnchorElements: 'snapshot',
  ImageElements: 'snapshot',
  LinkElements: 'snapshot',
  MetaElements: 'snapshot',
  ScriptElements: 'snapshot',
  IFrameElements: 'snapshot',
  FormElements: 'snapshot',
  MainDocumentContent: 'navigation',
  GlobalListeners: 'navigation',
  AppCacheManifest: 'snapshot',
  Doctype: 'snapshot',
  DOMStats: 'snapshot',
  OptimizedImages: 'navigation',
  PasswordInputsWithPreventedPaste: 'snapshot',
  ResponseCompression: 'navigation',
  TagsBlockingFirstPaint: 'navigation',
  FontSize: 'snapshot',
  EmbeddedContent: 'navigation',
  RobotsTxt: 'snapshot',
  TapTargets: 'snapshot',
  Accessibility: 'snapshot',
  TraceElements: 'navigation',
  InspectorIssues: 'navigation',
  SourceMaps: 'navigation',
  ServiceWorker: 'navigation',
  Offline: 'navigation',
  StartUrl: 'navigation',
  HTTPRedirect: 'navigation',
  HTMLWithoutJavaScript: 'navigation',
};
